### ISSUE TITLE
Seattle center maps are missing?

### ISSUE THREAD

**Issue by ocheyette** [dark/faa-mva-kml#4]
ZSE is missing. S46 only covers the tracon area.

**Comment by dark** [comment]
That's correct. The FAA website (https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/mva_mia/mva/) includes maps for S46 but not for ZSE.

We have to wait for the FAA to publish those data.

**Comment by ocheyette** [comment]
They seem to now have all the ARTCC maps here: https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/mva_mia/mia/

Looks like it could be a one-line addition to the regenerate-all script, adding another wget after line 95

Very nice tool.

**Comment by dark** [comment]
Thanks for the link, that works indeed.
Adding support now.

**Comment by dark** [comment]
I have added generated contentpacks for the MIA maps, including the one for ZSE.
